package com.zifisense.jll.dao;

import com.zifisense.jll.model.AlarmRecord;
import com.zifisense.jll.model.AlarmRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int countByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int deleteByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int insert(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int insertSelective(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    List<AlarmRecord> selectByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    AlarmRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AlarmRecord record, @Param("example") AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AlarmRecord record, @Param("example") AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlarmRecord record);
}