package com.zifisense.jll.dao;

import com.zifisense.jll.model.BusinessGroupAccount;
import com.zifisense.jll.model.BusinessGroupAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessGroupAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int countByExample(BusinessGroupAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessGroupAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int insert(BusinessGroupAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int insertSelective(BusinessGroupAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    List<BusinessGroupAccount> selectByExample(BusinessGroupAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    BusinessGroupAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessGroupAccount record, @Param("example") BusinessGroupAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessGroupAccount record, @Param("example") BusinessGroupAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessGroupAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessGroupAccount record);
}