package com.zifisense.jll.dao;

import com.zifisense.jll.model.BusinessGroup;
import com.zifisense.jll.model.BusinessGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int countByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int insert(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int insertSelective(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    List<BusinessGroup> selectByExample(BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    BusinessGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessGroup record, @Param("example") BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessGroup record, @Param("example") BusinessGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessGroup record);
}