package com.zifisense.jll.dao;

import com.zifisense.jll.model.MenuRole;
import com.zifisense.jll.model.MenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int countByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int deleteByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int insertSelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    List<MenuRole> selectByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    MenuRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MenuRole record, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MenuRole record, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuRole record);
}