package com.zifisense.jll.dao;

import com.zifisense.jll.model.ProjectAccount;
import com.zifisense.jll.model.ProjectAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int countByExample(ProjectAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int insert(ProjectAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int insertSelective(ProjectAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    List<ProjectAccount> selectByExample(ProjectAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    ProjectAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectAccount record, @Param("example") ProjectAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectAccount record, @Param("example") ProjectAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectAccount record);
}