package com.zifisense.jll.model;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_name_cn
     *
     * @mbggenerated
     */
    private String userNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_name_en
     *
     * @mbggenerated
     */
    private String userNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_position
     *
     * @mbggenerated
     */
    private String userPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.head_img_path
     *
     * @mbggenerated
     */
    private String headImgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.login_number
     *
     * @mbggenerated
     */
    private Integer loginNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.modify_user
     *
     * @mbggenerated
     */
    private Long modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name_model
     *
     * @mbggenerated
     */
    private Integer nameModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_update_pw
     *
     * @mbggenerated
     */
    private Date lastUpdatePw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_name_cn
     *
     * @return the value of account.user_name_cn
     *
     * @mbggenerated
     */
    public String getUserNameCn() {
        return userNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_name_cn
     *
     * @param userNameCn the value for account.user_name_cn
     *
     * @mbggenerated
     */
    public void setUserNameCn(String userNameCn) {
        this.userNameCn = userNameCn == null ? null : userNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_name_en
     *
     * @return the value of account.user_name_en
     *
     * @mbggenerated
     */
    public String getUserNameEn() {
        return userNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_name_en
     *
     * @param userNameEn the value for account.user_name_en
     *
     * @mbggenerated
     */
    public void setUserNameEn(String userNameEn) {
        this.userNameEn = userNameEn == null ? null : userNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account
     *
     * @return the value of account.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account
     *
     * @param account the value for account.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.salt
     *
     * @return the value of account.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.salt
     *
     * @param salt the value for account.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile_phone
     *
     * @return the value of account.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile_phone
     *
     * @param mobilePhone the value for account.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_position
     *
     * @return the value of account.user_position
     *
     * @mbggenerated
     */
    public String getUserPosition() {
        return userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_position
     *
     * @param userPosition the value for account.user_position
     *
     * @mbggenerated
     */
    public void setUserPosition(String userPosition) {
        this.userPosition = userPosition == null ? null : userPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.head_img_path
     *
     * @return the value of account.head_img_path
     *
     * @mbggenerated
     */
    public String getHeadImgPath() {
        return headImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.head_img_path
     *
     * @param headImgPath the value for account.head_img_path
     *
     * @mbggenerated
     */
    public void setHeadImgPath(String headImgPath) {
        this.headImgPath = headImgPath == null ? null : headImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.login_number
     *
     * @return the value of account.login_number
     *
     * @mbggenerated
     */
    public Integer getLoginNumber() {
        return loginNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.login_number
     *
     * @param loginNumber the value for account.login_number
     *
     * @mbggenerated
     */
    public void setLoginNumber(Integer loginNumber) {
        this.loginNumber = loginNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.login_time
     *
     * @return the value of account.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.login_time
     *
     * @param loginTime the value for account.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login_time
     *
     * @return the value of account.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login_time
     *
     * @param lastLoginTime the value for account.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.state
     *
     * @return the value of account.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.state
     *
     * @param state the value for account.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_user
     *
     * @return the value of account.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_user
     *
     * @param createUser the value for account.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.modify_user
     *
     * @return the value of account.modify_user
     *
     * @mbggenerated
     */
    public Long getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.modify_user
     *
     * @param modifyUser the value for account.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Long modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.modify_time
     *
     * @return the value of account.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.modify_time
     *
     * @param modifyTime the value for account.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name_model
     *
     * @return the value of account.name_model
     *
     * @mbggenerated
     */
    public Integer getNameModel() {
        return nameModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name_model
     *
     * @param nameModel the value for account.name_model
     *
     * @mbggenerated
     */
    public void setNameModel(Integer nameModel) {
        this.nameModel = nameModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_update_pw
     *
     * @return the value of account.last_update_pw
     *
     * @mbggenerated
     */
    public Date getLastUpdatePw() {
        return lastUpdatePw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_update_pw
     *
     * @param lastUpdatePw the value for account.last_update_pw
     *
     * @mbggenerated
     */
    public void setLastUpdatePw(Date lastUpdatePw) {
        this.lastUpdatePw = lastUpdatePw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userNameCn=").append(userNameCn);
        sb.append(", userNameEn=").append(userNameEn);
        sb.append(", account=").append(account);
        sb.append(", salt=").append(salt);
        sb.append(", password=").append(password);
        sb.append(", mobilePhone=").append(mobilePhone);
        sb.append(", email=").append(email);
        sb.append(", userPosition=").append(userPosition);
        sb.append(", headImgPath=").append(headImgPath);
        sb.append(", loginNumber=").append(loginNumber);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", state=").append(state);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", nameModel=").append(nameModel);
        sb.append(", lastUpdatePw=").append(lastUpdatePw);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}