package com.zifisense.jll.model;

import java.io.Serializable;
import java.util.Date;

public class AccountPasswordRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.password_old
     *
     * @mbggenerated
     */
    private String passwordOld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.password_new
     *
     * @mbggenerated
     */
    private String passwordNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.account_id
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_password_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_password_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.id
     *
     * @return the value of account_password_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.id
     *
     * @param id the value for account_password_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.password_old
     *
     * @return the value of account_password_record.password_old
     *
     * @mbggenerated
     */
    public String getPasswordOld() {
        return passwordOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.password_old
     *
     * @param passwordOld the value for account_password_record.password_old
     *
     * @mbggenerated
     */
    public void setPasswordOld(String passwordOld) {
        this.passwordOld = passwordOld == null ? null : passwordOld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.password_new
     *
     * @return the value of account_password_record.password_new
     *
     * @mbggenerated
     */
    public String getPasswordNew() {
        return passwordNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.password_new
     *
     * @param passwordNew the value for account_password_record.password_new
     *
     * @mbggenerated
     */
    public void setPasswordNew(String passwordNew) {
        this.passwordNew = passwordNew == null ? null : passwordNew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.account_id
     *
     * @return the value of account_password_record.account_id
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.account_id
     *
     * @param accountId the value for account_password_record.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.type
     *
     * @return the value of account_password_record.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.type
     *
     * @param type the value for account_password_record.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_password_record.create_time
     *
     * @return the value of account_password_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_password_record.create_time
     *
     * @param createTime the value for account_password_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", passwordOld=").append(passwordOld);
        sb.append(", passwordNew=").append(passwordNew);
        sb.append(", accountId=").append(accountId);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}