package com.zifisense.jll.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlarmRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public AlarmRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdIsNull() {
            addCriterion("app_source_id is null");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdIsNotNull() {
            addCriterion("app_source_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdEqualTo(Long value) {
            addCriterion("app_source_id =", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdNotEqualTo(Long value) {
            addCriterion("app_source_id <>", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdGreaterThan(Long value) {
            addCriterion("app_source_id >", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("app_source_id >=", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdLessThan(Long value) {
            addCriterion("app_source_id <", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdLessThanOrEqualTo(Long value) {
            addCriterion("app_source_id <=", value, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdIn(List<Long> values) {
            addCriterion("app_source_id in", values, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdNotIn(List<Long> values) {
            addCriterion("app_source_id not in", values, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdBetween(Long value1, Long value2) {
            addCriterion("app_source_id between", value1, value2, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceIdNotBetween(Long value1, Long value2) {
            addCriterion("app_source_id not between", value1, value2, "appSourceId");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeIsNull() {
            addCriterion("app_source_code is null");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeIsNotNull() {
            addCriterion("app_source_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeEqualTo(String value) {
            addCriterion("app_source_code =", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeNotEqualTo(String value) {
            addCriterion("app_source_code <>", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeGreaterThan(String value) {
            addCriterion("app_source_code >", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_source_code >=", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeLessThan(String value) {
            addCriterion("app_source_code <", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeLessThanOrEqualTo(String value) {
            addCriterion("app_source_code <=", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeLike(String value) {
            addCriterion("app_source_code like", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeNotLike(String value) {
            addCriterion("app_source_code not like", value, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeIn(List<String> values) {
            addCriterion("app_source_code in", values, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeNotIn(List<String> values) {
            addCriterion("app_source_code not in", values, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeBetween(String value1, String value2) {
            addCriterion("app_source_code between", value1, value2, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceCodeNotBetween(String value1, String value2) {
            addCriterion("app_source_code not between", value1, value2, "appSourceCode");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameIsNull() {
            addCriterion("app_source_name is null");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameIsNotNull() {
            addCriterion("app_source_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameEqualTo(String value) {
            addCriterion("app_source_name =", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameNotEqualTo(String value) {
            addCriterion("app_source_name <>", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameGreaterThan(String value) {
            addCriterion("app_source_name >", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_source_name >=", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameLessThan(String value) {
            addCriterion("app_source_name <", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameLessThanOrEqualTo(String value) {
            addCriterion("app_source_name <=", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameLike(String value) {
            addCriterion("app_source_name like", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameNotLike(String value) {
            addCriterion("app_source_name not like", value, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameIn(List<String> values) {
            addCriterion("app_source_name in", values, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameNotIn(List<String> values) {
            addCriterion("app_source_name not in", values, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameBetween(String value1, String value2) {
            addCriterion("app_source_name between", value1, value2, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andAppSourceNameNotBetween(String value1, String value2) {
            addCriterion("app_source_name not between", value1, value2, "appSourceName");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeIsNull() {
            addCriterion("sys_project_code is null");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeIsNotNull() {
            addCriterion("sys_project_code is not null");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeEqualTo(String value) {
            addCriterion("sys_project_code =", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeNotEqualTo(String value) {
            addCriterion("sys_project_code <>", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeGreaterThan(String value) {
            addCriterion("sys_project_code >", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sys_project_code >=", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeLessThan(String value) {
            addCriterion("sys_project_code <", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeLessThanOrEqualTo(String value) {
            addCriterion("sys_project_code <=", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeLike(String value) {
            addCriterion("sys_project_code like", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeNotLike(String value) {
            addCriterion("sys_project_code not like", value, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeIn(List<String> values) {
            addCriterion("sys_project_code in", values, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeNotIn(List<String> values) {
            addCriterion("sys_project_code not in", values, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeBetween(String value1, String value2) {
            addCriterion("sys_project_code between", value1, value2, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andSysProjectCodeNotBetween(String value1, String value2) {
            addCriterion("sys_project_code not between", value1, value2, "sysProjectCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("device_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("device_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("device_type =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("device_type <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("device_type >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("device_type <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("device_type <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("device_type like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("device_type not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("device_type in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("device_type not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("device_type between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("device_type not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andCmptMacIsNull() {
            addCriterion("cmpt_mac is null");
            return (Criteria) this;
        }

        public Criteria andCmptMacIsNotNull() {
            addCriterion("cmpt_mac is not null");
            return (Criteria) this;
        }

        public Criteria andCmptMacEqualTo(String value) {
            addCriterion("cmpt_mac =", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacNotEqualTo(String value) {
            addCriterion("cmpt_mac <>", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacGreaterThan(String value) {
            addCriterion("cmpt_mac >", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacGreaterThanOrEqualTo(String value) {
            addCriterion("cmpt_mac >=", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacLessThan(String value) {
            addCriterion("cmpt_mac <", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacLessThanOrEqualTo(String value) {
            addCriterion("cmpt_mac <=", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacLike(String value) {
            addCriterion("cmpt_mac like", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacNotLike(String value) {
            addCriterion("cmpt_mac not like", value, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacIn(List<String> values) {
            addCriterion("cmpt_mac in", values, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacNotIn(List<String> values) {
            addCriterion("cmpt_mac not in", values, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacBetween(String value1, String value2) {
            addCriterion("cmpt_mac between", value1, value2, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andCmptMacNotBetween(String value1, String value2) {
            addCriterion("cmpt_mac not between", value1, value2, "cmptMac");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressIsNull() {
            addCriterion("device_address is null");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressIsNotNull() {
            addCriterion("device_address is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressEqualTo(String value) {
            addCriterion("device_address =", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressNotEqualTo(String value) {
            addCriterion("device_address <>", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressGreaterThan(String value) {
            addCriterion("device_address >", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressGreaterThanOrEqualTo(String value) {
            addCriterion("device_address >=", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressLessThan(String value) {
            addCriterion("device_address <", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressLessThanOrEqualTo(String value) {
            addCriterion("device_address <=", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressLike(String value) {
            addCriterion("device_address like", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressNotLike(String value) {
            addCriterion("device_address not like", value, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressIn(List<String> values) {
            addCriterion("device_address in", values, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressNotIn(List<String> values) {
            addCriterion("device_address not in", values, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressBetween(String value1, String value2) {
            addCriterion("device_address between", value1, value2, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceAddressNotBetween(String value1, String value2) {
            addCriterion("device_address not between", value1, value2, "deviceAddress");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIsNull() {
            addCriterion("alarm_content is null");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIsNotNull() {
            addCriterion("alarm_content is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmContentEqualTo(String value) {
            addCriterion("alarm_content =", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotEqualTo(String value) {
            addCriterion("alarm_content <>", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentGreaterThan(String value) {
            addCriterion("alarm_content >", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentGreaterThanOrEqualTo(String value) {
            addCriterion("alarm_content >=", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLessThan(String value) {
            addCriterion("alarm_content <", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLessThanOrEqualTo(String value) {
            addCriterion("alarm_content <=", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLike(String value) {
            addCriterion("alarm_content like", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotLike(String value) {
            addCriterion("alarm_content not like", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIn(List<String> values) {
            addCriterion("alarm_content in", values, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotIn(List<String> values) {
            addCriterion("alarm_content not in", values, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentBetween(String value1, String value2) {
            addCriterion("alarm_content between", value1, value2, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotBetween(String value1, String value2) {
            addCriterion("alarm_content not between", value1, value2, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIsNull() {
            addCriterion("alarm_time is null");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIsNotNull() {
            addCriterion("alarm_time is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeEqualTo(Date value) {
            addCriterion("alarm_time =", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotEqualTo(Date value) {
            addCriterion("alarm_time <>", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeGreaterThan(Date value) {
            addCriterion("alarm_time >", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("alarm_time >=", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeLessThan(Date value) {
            addCriterion("alarm_time <", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeLessThanOrEqualTo(Date value) {
            addCriterion("alarm_time <=", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIn(List<Date> values) {
            addCriterion("alarm_time in", values, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotIn(List<Date> values) {
            addCriterion("alarm_time not in", values, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeBetween(Date value1, Date value2) {
            addCriterion("alarm_time between", value1, value2, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotBetween(Date value1, Date value2) {
            addCriterion("alarm_time not between", value1, value2, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("data_type is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("data_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Integer value) {
            addCriterion("data_type =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Integer value) {
            addCriterion("data_type <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Integer value) {
            addCriterion("data_type >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_type >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Integer value) {
            addCriterion("data_type <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Integer value) {
            addCriterion("data_type <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Integer> values) {
            addCriterion("data_type in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Integer> values) {
            addCriterion("data_type not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Integer value1, Integer value2) {
            addCriterion("data_type between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("data_type not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andAlarmYmIsNull() {
            addCriterion("alarm_ym is null");
            return (Criteria) this;
        }

        public Criteria andAlarmYmIsNotNull() {
            addCriterion("alarm_ym is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmYmEqualTo(Integer value) {
            addCriterion("alarm_ym =", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmNotEqualTo(Integer value) {
            addCriterion("alarm_ym <>", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmGreaterThan(Integer value) {
            addCriterion("alarm_ym >", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_ym >=", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmLessThan(Integer value) {
            addCriterion("alarm_ym <", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_ym <=", value, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmIn(List<Integer> values) {
            addCriterion("alarm_ym in", values, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmNotIn(List<Integer> values) {
            addCriterion("alarm_ym not in", values, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmBetween(Integer value1, Integer value2) {
            addCriterion("alarm_ym between", value1, value2, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYmNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_ym not between", value1, value2, "alarmYm");
            return (Criteria) this;
        }

        public Criteria andAlarmYearIsNull() {
            addCriterion("alarm_year is null");
            return (Criteria) this;
        }

        public Criteria andAlarmYearIsNotNull() {
            addCriterion("alarm_year is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmYearEqualTo(Integer value) {
            addCriterion("alarm_year =", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearNotEqualTo(Integer value) {
            addCriterion("alarm_year <>", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearGreaterThan(Integer value) {
            addCriterion("alarm_year >", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_year >=", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearLessThan(Integer value) {
            addCriterion("alarm_year <", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_year <=", value, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearIn(List<Integer> values) {
            addCriterion("alarm_year in", values, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearNotIn(List<Integer> values) {
            addCriterion("alarm_year not in", values, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearBetween(Integer value1, Integer value2) {
            addCriterion("alarm_year between", value1, value2, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmYearNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_year not between", value1, value2, "alarmYear");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthIsNull() {
            addCriterion("alarm_month is null");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthIsNotNull() {
            addCriterion("alarm_month is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthEqualTo(Integer value) {
            addCriterion("alarm_month =", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthNotEqualTo(Integer value) {
            addCriterion("alarm_month <>", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthGreaterThan(Integer value) {
            addCriterion("alarm_month >", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_month >=", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthLessThan(Integer value) {
            addCriterion("alarm_month <", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_month <=", value, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthIn(List<Integer> values) {
            addCriterion("alarm_month in", values, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthNotIn(List<Integer> values) {
            addCriterion("alarm_month not in", values, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthBetween(Integer value1, Integer value2) {
            addCriterion("alarm_month between", value1, value2, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_month not between", value1, value2, "alarmMonth");
            return (Criteria) this;
        }

        public Criteria andAlarmDayIsNull() {
            addCriterion("alarm_day is null");
            return (Criteria) this;
        }

        public Criteria andAlarmDayIsNotNull() {
            addCriterion("alarm_day is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmDayEqualTo(Integer value) {
            addCriterion("alarm_day =", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayNotEqualTo(Integer value) {
            addCriterion("alarm_day <>", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayGreaterThan(Integer value) {
            addCriterion("alarm_day >", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_day >=", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayLessThan(Integer value) {
            addCriterion("alarm_day <", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_day <=", value, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayIn(List<Integer> values) {
            addCriterion("alarm_day in", values, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayNotIn(List<Integer> values) {
            addCriterion("alarm_day not in", values, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayBetween(Integer value1, Integer value2) {
            addCriterion("alarm_day between", value1, value2, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmDayNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_day not between", value1, value2, "alarmDay");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIsNull() {
            addCriterion("alarm_type is null");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIsNotNull() {
            addCriterion("alarm_type is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeEqualTo(String value) {
            addCriterion("alarm_type =", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotEqualTo(String value) {
            addCriterion("alarm_type <>", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeGreaterThan(String value) {
            addCriterion("alarm_type >", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("alarm_type >=", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLessThan(String value) {
            addCriterion("alarm_type <", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLessThanOrEqualTo(String value) {
            addCriterion("alarm_type <=", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLike(String value) {
            addCriterion("alarm_type like", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotLike(String value) {
            addCriterion("alarm_type not like", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIn(List<String> values) {
            addCriterion("alarm_type in", values, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotIn(List<String> values) {
            addCriterion("alarm_type not in", values, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeBetween(String value1, String value2) {
            addCriterion("alarm_type between", value1, value2, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotBetween(String value1, String value2) {
            addCriterion("alarm_type not between", value1, value2, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmStateIsNull() {
            addCriterion("alarm_state is null");
            return (Criteria) this;
        }

        public Criteria andAlarmStateIsNotNull() {
            addCriterion("alarm_state is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmStateEqualTo(Long value) {
            addCriterion("alarm_state =", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateNotEqualTo(Long value) {
            addCriterion("alarm_state <>", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateGreaterThan(Long value) {
            addCriterion("alarm_state >", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateGreaterThanOrEqualTo(Long value) {
            addCriterion("alarm_state >=", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateLessThan(Long value) {
            addCriterion("alarm_state <", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateLessThanOrEqualTo(Long value) {
            addCriterion("alarm_state <=", value, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateIn(List<Long> values) {
            addCriterion("alarm_state in", values, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateNotIn(List<Long> values) {
            addCriterion("alarm_state not in", values, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateBetween(Long value1, Long value2) {
            addCriterion("alarm_state between", value1, value2, "alarmState");
            return (Criteria) this;
        }

        public Criteria andAlarmStateNotBetween(Long value1, Long value2) {
            addCriterion("alarm_state not between", value1, value2, "alarmState");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(Long value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(Long value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(Long value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(Long value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(Long value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<Long> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<Long> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(Long value1, Long value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(Long value1, Long value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}