package com.zifisense.jll.model;

import java.io.Serializable;
import java.util.Date;

public class AlarmRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.app_source_id
     *
     * @mbggenerated
     */
    private Long appSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.app_source_code
     *
     * @mbggenerated
     */
    private String appSourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.app_source_name
     *
     * @mbggenerated
     */
    private String appSourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.sys_project_code
     *
     * @mbggenerated
     */
    private String sysProjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.device_type
     *
     * @mbggenerated
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.cmpt_mac
     *
     * @mbggenerated
     */
    private String cmptMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.device_address
     *
     * @mbggenerated
     */
    private String deviceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_content
     *
     * @mbggenerated
     */
    private String alarmContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_time
     *
     * @mbggenerated
     */
    private Date alarmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_ym
     *
     * @mbggenerated
     */
    private Integer alarmYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_year
     *
     * @mbggenerated
     */
    private Integer alarmYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_month
     *
     * @mbggenerated
     */
    private Integer alarmMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_day
     *
     * @mbggenerated
     */
    private Integer alarmDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_type
     *
     * @mbggenerated
     */
    private String alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_state
     *
     * @mbggenerated
     */
    private Long alarmState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.modify_user
     *
     * @mbggenerated
     */
    private Long modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.id
     *
     * @return the value of alarm_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.id
     *
     * @param id the value for alarm_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.project_name
     *
     * @return the value of alarm_record.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.project_name
     *
     * @param projectName the value for alarm_record.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.project_id
     *
     * @return the value of alarm_record.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.project_id
     *
     * @param projectId the value for alarm_record.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.app_source_id
     *
     * @return the value of alarm_record.app_source_id
     *
     * @mbggenerated
     */
    public Long getAppSourceId() {
        return appSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.app_source_id
     *
     * @param appSourceId the value for alarm_record.app_source_id
     *
     * @mbggenerated
     */
    public void setAppSourceId(Long appSourceId) {
        this.appSourceId = appSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.app_source_code
     *
     * @return the value of alarm_record.app_source_code
     *
     * @mbggenerated
     */
    public String getAppSourceCode() {
        return appSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.app_source_code
     *
     * @param appSourceCode the value for alarm_record.app_source_code
     *
     * @mbggenerated
     */
    public void setAppSourceCode(String appSourceCode) {
        this.appSourceCode = appSourceCode == null ? null : appSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.app_source_name
     *
     * @return the value of alarm_record.app_source_name
     *
     * @mbggenerated
     */
    public String getAppSourceName() {
        return appSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.app_source_name
     *
     * @param appSourceName the value for alarm_record.app_source_name
     *
     * @mbggenerated
     */
    public void setAppSourceName(String appSourceName) {
        this.appSourceName = appSourceName == null ? null : appSourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.sys_project_code
     *
     * @return the value of alarm_record.sys_project_code
     *
     * @mbggenerated
     */
    public String getSysProjectCode() {
        return sysProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.sys_project_code
     *
     * @param sysProjectCode the value for alarm_record.sys_project_code
     *
     * @mbggenerated
     */
    public void setSysProjectCode(String sysProjectCode) {
        this.sysProjectCode = sysProjectCode == null ? null : sysProjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.device_type
     *
     * @return the value of alarm_record.device_type
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.device_type
     *
     * @param deviceType the value for alarm_record.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.cmpt_mac
     *
     * @return the value of alarm_record.cmpt_mac
     *
     * @mbggenerated
     */
    public String getCmptMac() {
        return cmptMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.cmpt_mac
     *
     * @param cmptMac the value for alarm_record.cmpt_mac
     *
     * @mbggenerated
     */
    public void setCmptMac(String cmptMac) {
        this.cmptMac = cmptMac == null ? null : cmptMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.device_address
     *
     * @return the value of alarm_record.device_address
     *
     * @mbggenerated
     */
    public String getDeviceAddress() {
        return deviceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.device_address
     *
     * @param deviceAddress the value for alarm_record.device_address
     *
     * @mbggenerated
     */
    public void setDeviceAddress(String deviceAddress) {
        this.deviceAddress = deviceAddress == null ? null : deviceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.device_id
     *
     * @return the value of alarm_record.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.device_id
     *
     * @param deviceId the value for alarm_record.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_content
     *
     * @return the value of alarm_record.alarm_content
     *
     * @mbggenerated
     */
    public String getAlarmContent() {
        return alarmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_content
     *
     * @param alarmContent the value for alarm_record.alarm_content
     *
     * @mbggenerated
     */
    public void setAlarmContent(String alarmContent) {
        this.alarmContent = alarmContent == null ? null : alarmContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_time
     *
     * @return the value of alarm_record.alarm_time
     *
     * @mbggenerated
     */
    public Date getAlarmTime() {
        return alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_time
     *
     * @param alarmTime the value for alarm_record.alarm_time
     *
     * @mbggenerated
     */
    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.data_type
     *
     * @return the value of alarm_record.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.data_type
     *
     * @param dataType the value for alarm_record.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_ym
     *
     * @return the value of alarm_record.alarm_ym
     *
     * @mbggenerated
     */
    public Integer getAlarmYm() {
        return alarmYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_ym
     *
     * @param alarmYm the value for alarm_record.alarm_ym
     *
     * @mbggenerated
     */
    public void setAlarmYm(Integer alarmYm) {
        this.alarmYm = alarmYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_year
     *
     * @return the value of alarm_record.alarm_year
     *
     * @mbggenerated
     */
    public Integer getAlarmYear() {
        return alarmYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_year
     *
     * @param alarmYear the value for alarm_record.alarm_year
     *
     * @mbggenerated
     */
    public void setAlarmYear(Integer alarmYear) {
        this.alarmYear = alarmYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_month
     *
     * @return the value of alarm_record.alarm_month
     *
     * @mbggenerated
     */
    public Integer getAlarmMonth() {
        return alarmMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_month
     *
     * @param alarmMonth the value for alarm_record.alarm_month
     *
     * @mbggenerated
     */
    public void setAlarmMonth(Integer alarmMonth) {
        this.alarmMonth = alarmMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_day
     *
     * @return the value of alarm_record.alarm_day
     *
     * @mbggenerated
     */
    public Integer getAlarmDay() {
        return alarmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_day
     *
     * @param alarmDay the value for alarm_record.alarm_day
     *
     * @mbggenerated
     */
    public void setAlarmDay(Integer alarmDay) {
        this.alarmDay = alarmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_type
     *
     * @return the value of alarm_record.alarm_type
     *
     * @mbggenerated
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_type
     *
     * @param alarmType the value for alarm_record.alarm_type
     *
     * @mbggenerated
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_state
     *
     * @return the value of alarm_record.alarm_state
     *
     * @mbggenerated
     */
    public Long getAlarmState() {
        return alarmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_state
     *
     * @param alarmState the value for alarm_record.alarm_state
     *
     * @mbggenerated
     */
    public void setAlarmState(Long alarmState) {
        this.alarmState = alarmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.create_time
     *
     * @return the value of alarm_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.create_time
     *
     * @param createTime the value for alarm_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.modify_time
     *
     * @return the value of alarm_record.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.modify_time
     *
     * @param modifyTime the value for alarm_record.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.modify_user
     *
     * @return the value of alarm_record.modify_user
     *
     * @mbggenerated
     */
    public Long getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.modify_user
     *
     * @param modifyUser the value for alarm_record.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Long modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectId=").append(projectId);
        sb.append(", appSourceId=").append(appSourceId);
        sb.append(", appSourceCode=").append(appSourceCode);
        sb.append(", appSourceName=").append(appSourceName);
        sb.append(", sysProjectCode=").append(sysProjectCode);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", cmptMac=").append(cmptMac);
        sb.append(", deviceAddress=").append(deviceAddress);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", alarmContent=").append(alarmContent);
        sb.append(", alarmTime=").append(alarmTime);
        sb.append(", dataType=").append(dataType);
        sb.append(", alarmYm=").append(alarmYm);
        sb.append(", alarmYear=").append(alarmYear);
        sb.append(", alarmMonth=").append(alarmMonth);
        sb.append(", alarmDay=").append(alarmDay);
        sb.append(", alarmType=").append(alarmType);
        sb.append(", alarmState=").append(alarmState);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}