package com.zifisense.jll.model;

import java.io.Serializable;
import java.util.Date;

public class BusinessGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.group_name_cn
     *
     * @mbggenerated
     */
    private String groupNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.group_name_en
     *
     * @mbggenerated
     */
    private String groupNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.group_code
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.name_model
     *
     * @mbggenerated
     */
    private Integer nameModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_group.modify_user
     *
     * @mbggenerated
     */
    private Long modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.id
     *
     * @return the value of business_group.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.id
     *
     * @param id the value for business_group.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.group_name_cn
     *
     * @return the value of business_group.group_name_cn
     *
     * @mbggenerated
     */
    public String getGroupNameCn() {
        return groupNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.group_name_cn
     *
     * @param groupNameCn the value for business_group.group_name_cn
     *
     * @mbggenerated
     */
    public void setGroupNameCn(String groupNameCn) {
        this.groupNameCn = groupNameCn == null ? null : groupNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.group_name_en
     *
     * @return the value of business_group.group_name_en
     *
     * @mbggenerated
     */
    public String getGroupNameEn() {
        return groupNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.group_name_en
     *
     * @param groupNameEn the value for business_group.group_name_en
     *
     * @mbggenerated
     */
    public void setGroupNameEn(String groupNameEn) {
        this.groupNameEn = groupNameEn == null ? null : groupNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.group_code
     *
     * @return the value of business_group.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.group_code
     *
     * @param groupCode the value for business_group.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.name_model
     *
     * @return the value of business_group.name_model
     *
     * @mbggenerated
     */
    public Integer getNameModel() {
        return nameModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.name_model
     *
     * @param nameModel the value for business_group.name_model
     *
     * @mbggenerated
     */
    public void setNameModel(Integer nameModel) {
        this.nameModel = nameModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.state
     *
     * @return the value of business_group.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.state
     *
     * @param state the value for business_group.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.create_user
     *
     * @return the value of business_group.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.create_user
     *
     * @param createUser the value for business_group.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.create_time
     *
     * @return the value of business_group.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.create_time
     *
     * @param createTime the value for business_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.modify_time
     *
     * @return the value of business_group.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.modify_time
     *
     * @param modifyTime the value for business_group.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_group.modify_user
     *
     * @return the value of business_group.modify_user
     *
     * @mbggenerated
     */
    public Long getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_group.modify_user
     *
     * @param modifyUser the value for business_group.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Long modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupNameCn=").append(groupNameCn);
        sb.append(", groupNameEn=").append(groupNameEn);
        sb.append(", groupCode=").append(groupCode);
        sb.append(", nameModel=").append(nameModel);
        sb.append(", state=").append(state);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}